[build]
  command = "yarn rw build"
  publish = "web/dist"
  functions = "api/dist/functions"

[[plugins]]
  package = "netlify-plugin-prisma-provider"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
