[build]
  command = "yarn rw deploy netlify && yarn rw db up --no-db-client --auto-approve && yarn rw dataMigrate up"
  publish = "web/dist"
  functions = "api/dist/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
