[build]
  command = "yarn rw build"
  publish = "web/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-prisma-provider"

[functions]
  directory = "api/dist/functions"
